### ISSUE TITLE
Regarding installation process

### ISSUE THREAD

**Issue by samay-patel-2110** [IDEA-Research/TAPTR#10]
i have used the exact versions python=3.8.18,pytorch=1.13.0+cu117,cuda=11.7

but when i run pip install it shows the problem below

ERROR: Ignored the following versions that require a different python version: 1.2.0 Requires-Python >=3.9; 1.2.1 Requires-Python >=3.9; 1.2.1rc1 Requires-Python >=3.9; 2.14.0 Requires-Python >=3.9; 2.14.0rc0 Requires-Python >=3.9; 3.0.0 Requires-Python >=3.9; 3.0.1 Requires-Python >=3.9; 3.0.2 Requires-Python >=3.9; 3.0.3 Requires-Python >=3.9; 3.0.4 Requires-Python >=3.9; 3.0.5 Requires-Python >=3.9; 3.1.0 Requires-Python >=3.9; 3.1.1 Requires-Python >=3.9; 3.2.0 Requires-Python >=3.9; 3.2.1 Requires-Python >=3.9; 3.3.0 Requires-Python >=3.9; 3.3.1 Requires-Python >=3.9; 3.3.2 Requires-Python >=3.9; 3.3.3 Requires-Python >=3.9; 3.4.0 Requires-Python >=3.9; 3.4.1 Requires-Python >=3.9; 3.8.0 Requires-Python >=3.9; 3.8.0rc1 Requires-Python >=3.9; 3.8.1 Requires-Python >=3.9; 3.8.2 Requires-Python >=3.9; 3.8.3 Requires-Python >=3.9; 3.8.4 Requires-Python >=3.9; 3.9.0 Requires-Python >=3.9; 3.9.0rc2 Requires-Python >=3.9; 3.9.1 Requires-Python >=3.9; 3.9.1.post1 Requires-Python >=3.9; 8.13.1 Requires-Python >=3.9; 8.13.2 Requires-Python >=3.9; 8.14.0 Requires-Python >=3.9; 8.15.0 Requires-Python >=3.9; 8.16.0 Requires-Python >=3.9; 8.16.1 Requires-Python >=3.9; 8.17.0 Requires-Python >=3.9; 8.17.1 Requires-Python >=3.9; 8.17.2 Requires-Python >=3.9; 8.18.0 Requires-Python >=3.9; 8.18.1 Requires-Python >=3.9; 8.19.0 Requires-Python >=3.10; 8.20.0 Requires-Python >=3.10; 8.21.0 Requires-Python >=3.10; 8.22.0 Requires-Python >=3.10; 8.22.1 Requires-Python >=3.10; 8.22.2 Requires-Python >=3.10; 8.23.0 Requires-Python >=3.10; 8.24.0 Requires-Python >=3.10; 8.25.0 Requires-Python >=3.10; 8.26.0 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement MultiScaleDeformableAttention==1.0 (from versions: none)
ERROR: No matching distribution found for MultiScaleDeformableAttention==1.0

**Comment by lukaboljevic** [comment]
Hello. I suggest you remove the `MultiScaleDeformableAttention==1.0` line from `requirements.txt` and install it manually, as it should be. Installation instructrions should be in [the Installation section of the README](https://github.com/IDEA-Research/TAPTR?tab=readme-ov-file#installation), or you can also follow instructions in e.g. the [Deformable DETR repository](https://github.com/fundamentalvision/Deformable-DETR?tab=readme-ov-file#compiling-cuda-operators).

**Comment by LHY-HongyangLi** [comment]
Thank you @lukaboljevic ,
Yes, @samay-patel-2110 you should manually install MultiScaleDeformableAttention through the commend 
'''
python setup.py install
'''
as we have mentioned in the installation section.

**Comment by sinkers-lan** [comment]
Thanks to @LHY-HongyangLi and @lukaboljevic for your kind guidance. For `MultiScaleDeformableAttention==1.0`, we should remove it from `requirements.txt` and install it via `python setup.py install` according to [the Installation section of the README](https://github.com/IDEA-Research/TAPTR?tab=readme-ov-file#installation). Then I got:

![image](https://github.com/user-attachments/assets/b03128c5-b971-4259-be6e-5ac4e8e13528)

**Comment by LHY-HongyangLi** [comment]
Hi, @sinkers-lan ,
This means that you have installed the MultiScaleDeformableAttention successfully.

**Comment by sinkers-lan** [comment]
> Hi, @sinkers-lan , This means that you have installed the MultiScaleDeformableAttention successfully.

Hi, @LHY-HongyangLi,

That’s right, I can now run the code successfully. Thank you!

**Comment by LHY-HongyangLi** [comment]
I will close this issue. If you have any further question, feel free to reopen it or reach out.😉
