### ISSUE TITLE
Is the TAPTRv2 checkpoint uploaded?

### ISSUE THREAD

**Issue by jun297** [IDEA-Research/TAPTR#12]
Hi, thank you for sharing your great work!
I think the uploaded checkpoint in this link (https://drive.google.com/file/d/1sb4BXpCsYe6au_2a1M77tapdkodh48Rm/view?usp=share_link) is TAPTRv1
Where can I get the v2 checkpoint?

**Comment by LHY-HongyangLi** [comment]
I'm sorry for the late reply, we have uploaded the checkpoint, you can find it in the v2 branch.

I'll close this issue. If you have any further question, feel free to reopen it.
