### ISSUE TITLE
TAPTRv3 paper not found

### ISSUE THREAD

**Issue by AravindhPadmanabhan** [IDEA-Research/TAPTR#14]
Hi, I am not able to find the paper on TAPTRv3 although the README says it has been uploaded. The link says that the file is not found. Please look into this. Thank you!

**Comment by JinyuanQu** [comment]
Hi @AravindhPadmanabhan, thanks for your attention.
You can find the paper on TAPTRv3 here: https://github.com/IDEA-Research/TAPTR/blob/v3/TAPTRv3.pdf

**Comment by LHY-HongyangLi** [comment]
Hi @AravindhPadmanabhan ,
I'll close this issue. If you have any further question, feel free to reopen it.
