### ISSUE TITLE
Training time of TAPTR

### ISSUE THREAD

**Issue by Kou-99** [IDEA-Research/TAPTR#15]
Hi, thank you for sharing your impressive work! Could you please provide the training time for TAPTR when using 8 A100 GPUs? Additionally, I'm curious if TAPTR requires the 80GB version of the A100 GPU?

**Comment by LHY-HongyangLi** [comment]
Hi @Kou-99, thank you for your attention. 

We train TAPTR on 8 A100 (80G) GPUs for about 3.5 days.

Unfortunately, we have to confess that the training phase of TAPTR is very source-consuming. We're dedicating ourselves to this issue, so stay tuned for further updates! If you have any good ideas to reduce memory consumption during training, feel free to reach out—we’d love to collaborate!

**Comment by Kou-99** [comment]
Thanks for your information! Looking forward to your further updates!
