### ISSUE TITLE
Where are the codes for TAPTR?

### ISSUE THREAD

**Issue by hiyyg** [IDEA-Research/TAPTR#16]

**Comment by LHY-HongyangLi** [comment]
Hi, thank you for your attention.

You can switch the branch of this repository to v1 or v2 to get the corresponding code.

**Comment by LHY-HongyangLi** [comment]
More specifically, their URLs are:

TAPTRv1:  https://github.com/IDEA-Research/TAPTR/tree/v1
TAPTRv2: https://github.com/IDEA-Research/TAPTR/tree/v2
TAPTRv3 has not been opensourced.

**Comment by LHY-HongyangLi** [comment]
I'll close this issue, if you have any further questions feel free to reopen it or open a new issue. 😉
