### ISSUE TITLE
Host demos on Huggingface Spaces

### ISSUE THREAD

**Issue by yvrjsharma** [IDEA-Research/TAPTR#6]
Hi @LHY-HongyangLi congratulations on TAPTR release! It would be amazing to have the demos hosted on Huggingface Spaces. We provide GPU grants for research-oriented projects and papers, and we would be happy to sponsor ZeroGPU (A100s) for hosting the TAPTR demos on Spaces.

- You will need to modify the demo code for ZeroGPU Spaces. To understand this better, please refer to the `usage` section of the organization: https://huggingface.co/zero-gpu-explorers.

- Here is a step-by-step guide for using the gradio sdk on Spaces: https://huggingface.co/docs/hub/en/spaces-sdks-gradio.

- For information on how to apply for GPU grants on Spaces, please visit: https://huggingface.co/docs/hub/en/spaces-gpus#community-gpu-grants."

**Comment by LHY-HongyangLi** [comment]
Hi @yvrjsharma,
Thank you for your kind invitation! We are very much looking forward to hosting our model on Huggingface. We will add this to our schedule and complete the deployment after finishing our current project (about 1 week later).

**Comment by NielsRogge** [comment]
Hi @LHY-HongyangLi,

Congrats on your work. Besides hosting a demo, are you also up for uploading the model to the hub, instead of Google Drive? This could enhance its discoverability as people can then find them when searching for tracking models on [hf.co/models](https://hf.co/models).

See here for a guide: https://huggingface.co/docs/hub/models-uploading.

It can also be linked to the paper page (where I discovered your work): https://huggingface.co/papers/2407.16291. See here on how to do that: https://huggingface.co/docs/hub/en/paper-pages#linking-a-paper-to-a-model-dataset-or-space.

Let us know if you need any help!

Cheers,

Niels
Open-source @ HF

**Comment by LHY-HongyangLi** [comment]
Dear @yvrjsharma and @NielsRogge ,
In the past month, we have been busy with another job, we are sorry for this late response to your kind invitation.
When we are trying to host our demo on HF, we find that we are not invited to 'ZeroGPU' group in huggingface, could you please do us a favor?

**Comment by yvrjsharma** [comment]
Hi @LHY-HongyangLi Can you share your Spaces link, we can try assigning a ZeroGPU to it. Also, you might need to modify the gradio demo code a bit for it to work as a ZeroGPU Space. To understand this better, please refer to the usage section of the organization: https://huggingface.co/zero-gpu-explorers.

**Comment by LHY-HongyangLi** [comment]
Hi @yvrjsharma,
Thank you for your early reply. My Spaces link is: https://huggingface.co/HYeungLee. Sure, we are modifying our demo code to suit the requirements in https://huggingface.co/zero-gpu-explorers.

**Comment by NielsRogge** [comment]
Hi @LHY-HongyangLi, coming back to this thread, would you be up for uploading the model to the hub, rather than Google Drive? Could be pushed here: https://huggingface.co/HYeungLee.

Next we could look into providing a Spaces demo, linked to the model

**Comment by LHY-HongyangLi** [comment]
Since we have deployed our demo on huggingface (https://huggingface.co/spaces/HYeungLee/TAPTR), I' close this issue.

**Comment by NielsRogge** [comment]
Thank you @LHY-HongyangLi !

However I noticed the model card is currently empty: https://huggingface.co/HYeungLee/TAPTR-Series.

Would you be up for adding a README, which links to https://huggingface.co/papers/2407.16291? You can also add metadata in the model card, for instance the following:
```
---
tags:
- vision
- object-tracking
---
```

**Comment by NielsRogge** [comment]
Also ideally, each model is pushed to a separate model repository. This way, we can link the v1 model to https://huggingface.co/papers/2403.13042 and the v2 model to https://huggingface.co/papers/2407.16291.

We can also enable download metrics for your models, if you prefer so. See https://huggingface.co/docs/hub/models-download-stats#can-i-add-my-query-files-for-my-library for details.

**Comment by LHY-HongyangLi** [comment]
Sure, we will do these later. Thank you for your kind reminder 😉.
