### ISSUE TITLE
Cotracker is Better Than This ...

### ISSUE THREAD

**Issue by AMEERAZAM08** [IDEA-Research/TAPTR#7]

**Comment by LHY-HongyangLi** [comment]
Hi @AMEERAZAM08 
Thank you for your interest in our work. Indeed, CoTracker is very powerful and serves as an important milestone in the field of TAP. Our method has been greatly inspired by Cotracker, and we must express our gratitude for CoTracker and its authors. 

The TAP community is still in its early stages, and each method has its own strengths and weaknesses. We welcome you to achieve your goals by combining the results of different methods. 

Finally, thank you for your attention to the TAP community. We will work even harder to improve the performance of the TAPTR series and contribute more to the development of the TAP field.

It would be our honor and motivation if TAPTR can bring any convenience to your work. Have fun with TAPTR!😉

**Comment by LHY-HongyangLi** [comment]
Hi @AMEERAZAM08 
I will close this issue, if you have any questions feel free to reopen it.
At the same time, if you find any consistent failure patterns, feel free to report them either in this issue or by opening a new one.
